[User API] Get User Profile
hyecheol123/CollegeMate-User-API pull request #19
Opened 2023-06-23 05:06 UTC by hse2527

Close #5 
Close #17 

## When Reviewing this PR, please
- checkout `feature-#5-steve` branch
- Thoroughly read the code and compare it with API documentation
- Thoroughly read the test code
- Check newly implemented datatypes
- Run the test code. Check the behavior and code coverage

2023-06-23 06:02 UTC, hse2527 commented
Error case when Origin header. Application key, and ServerToken are not present might need to be revised

2023-06-24 02:56 UTC, hyecheol123 requested changes
Major Changes are required.
- Base64Email were not properly handled
- Some other minor errors

Test cases are not reviewed.

2023-06-24 02:56 UTC, hyecheol123 commented on src/datatypes/User/User.ts
> +        query: `SELECT * FROM user WHERE user.email = "${email}"`,
Use Prepared Statement (SQL Injection)

2023-06-24 02:56 UTC, hyecheol123 commented on src/datatypes/User/User.ts
> +    return new User(
Constructor Specification Modified

2023-06-24 02:56 UTC, hyecheol123 commented on src/datatypes/User/UserProfileResponseObj.ts
> +  nicknameChanged?: Date | string;
Response should be in string

2023-06-24 02:56 UTC, hyecheol123 commented on src/functions/responseFormatter/formatUserProfileResponseObj.ts
Do we really need this function? This can be integrated with user router as this function is only called at one place.

2023-06-24 02:56 UTC, hyecheol123 commented on src/routes/user.ts
> +    } else {
Use if / else if / else

2023-06-24 02:56 UTC, hyecheol123 commented on src/routes/user.ts
> +    const requestUserEmail = req.params.base64Email;
base64Email should be converted to normal email

2023-06-25 16:47 UTC, hse2527 commented on src/functions/responseFormatter/formatUserProfileResponseObj.ts
deleted

2023-06-25 16:48 UTC, hse2527 commented on src/routes/user.ts
> +    const requestUserEmail = req.params.base64Email;
converted

2023-06-27 00:12 UTC, hyecheol123 requested changes
DO NOT CHANGE TESTCODE THAT I WROTE

2023-06-27 01:50 UTC, hyecheol123 approved these changes

2023-06-27 01:56 UTC, merged